# openapi.yaml
openapi: 3.1.0
info:
  title: Copper Print Gallery Content Management Service API
  version: 1.0.0
  description: API for managing galleries and copper print artworks in the Copper Print Gallery system

servers:
  - url: '{protocol}://{environment}.{domain}/api/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        enum:
          - dev
          - staging
          - prod
        default: prod
      domain:
        default: api.copperprintgallery.com
        description: Base domain for the API

paths:
  $ref: './paths.yaml'

components:
  schemas:
    $ref: './schemas.yaml'
  responses:
    $ref: './responses.yaml'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT