# openapi.yaml
openapi: 3.1.0
info:
  title: Copper Print Gallery Content Management Service API
  version: 1.0.0
  description: API for managing galleries and copper print artworks in the Copper Print Gallery system

servers:
  - url: '{protocol}://{environment}.{domain}/api/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      environment:
        enum:
          - dev
          - staging
          - prod
        default: prod
      domain:
        default: api.copperprintgallery.com
        description: Base domain for the API

paths:
  /galleries:
      get:
        summary: List copper print galleries
        description: Retrieves a list of all copper print galleries
        parameters:
          - $ref: '../parameters/pagination.yaml#/page'
          - $ref: '../parameters/pagination.yaml#/limit'
          - $ref: '../parameters/language.yaml#/language'
        responses:
          '200':
            $ref: '../responses/galleries.yaml#/GalleryListResponse'
          '400':
            $ref: '../responses/errors.yaml#/BadRequest'
      post:
        summary: Create a new copper print gallery
        description: Creates a new gallery for copper print artworks
        security:
          - BearerAuth: []
        requestBody:
          $ref: '../requestBodies/galleries.yaml#/GalleryCreate'
        responses:
          '201':
            $ref: '../responses/galleries.yaml#/GalleryResponse'
          '400':
            $ref: '../responses/errors.yaml#/BadRequest'
          '401':
            $ref: '../responses/errors.yaml#/Unauthorized'
          '403':
            $ref: '../responses/errors.yaml#/Forbidden'
  /galleries/{galleryId}:
      get:
        summary: Get copper print gallery details
        description: Retrieves details of a specific copper print gallery
        parameters:
          - $ref: '../parameters/path.yaml#/galleryId'
          - $ref: '../parameters/language.yaml#/language'
        responses:
          '200':
            $ref: '../responses/galleries.yaml#/GalleryDetailResponse'
          '404':
            $ref: '../responses/errors.yaml#/NotFound'
      put:
        summary: Update a copper print gallery
        description: Updates an existing copper print gallery
        security:
          - BearerAuth: []
        parameters:
          - $ref: '../parameters/path.yaml#/galleryId'
        requestBody:
          $ref: '../requestBodies/galleries.yaml#/GalleryUpdate'
        responses:
          '200':
            $ref: '../responses/galleries.yaml#/GalleryResponse'
          '400':
            $ref: '../responses/errors.yaml#/BadRequest'
          '401':
            $ref: '../responses/errors.yaml#/Unauthorized'
          '403':
            $ref: '../responses/errors.yaml#/Forbidden'
          '404':
            $ref: '../responses/errors.yaml#/NotFound'
      delete:
        summary: Delete a copper print gallery
        description: Deletes a copper print gallery
        security:
          - BearerAuth: []
        parameters:
          - $ref: '../parameters/path.yaml#/galleryId'
        responses:
          '204':
            description: Gallery deleted successfully
          '401':
            $ref: '../responses/errors.yaml#/Unauthorized'
          '403':
            $ref: '../responses/errors.yaml#/Forbidden'
          '404':
            $ref: '../responses/errors.yaml#/NotFound'
  /prints:
      get:
        summary: List copper prints
        description: Retrieves a list of all copper prints
        parameters:
          - $ref: '../parameters/pagination.yaml#/page'
          - $ref: '../parameters/pagination.yaml#/limit'
          - $ref: '../parameters/language.yaml#/language'
          - $ref: '../parameters/query.yaml#/galleryId'
          - $ref: '../parameters/query.yaml#/technique'
        responses:
          '200':
            $ref: '../responses/prints.yaml#/PrintListResponse'
          '400':
            $ref: '../responses/errors.yaml#/BadRequest'
      post:
        summary: Create a new copper print
        description: Creates a new copper print artwork
        security:
          - BearerAuth: [ ]
        requestBody:
          $ref: '../requestBodies/prints.yaml#/PrintCreate'
        responses:
          '201':
            $ref: '../responses/prints.yaml#/PrintResponse'
          '400':
            $ref: '../responses/errors.yaml#/BadRequest'
          '401':
            $ref: '../responses/errors.yaml#/Unauthorized'
          '403':
            $ref: '../responses/errors.yaml#/Forbidden'
  /prints/{printId}:
      get:
        summary: Get copper print details
        description: Retrieves details of a specific copper print
        parameters:
          - $ref: '../parameters/path.yaml#/printId'
          - $ref: '../parameters/language.yaml#/language'
        responses:
          '200':
            $ref: '../responses/prints.yaml#/PrintDetailResponse'
          '404':
            $ref: '../responses/errors.yaml#/NotFound'
      put:
        summary: Update a copper print
        description: Updates an existing copper print
        security:
          - BearerAuth: [ ]
        parameters:
          - $ref: '../parameters/path.yaml#/printId'
        requestBody:
          $ref: '../requestBodies/prints.yaml#/PrintUpdate'
        responses:
          '200':
            $ref: '../responses/prints.yaml#/PrintResponse'
          '400':
            $ref: '../responses/errors.yaml#/BadRequest'
          '401':
            $ref: '../responses/errors.yaml#/Unauthorized'
          '403':
            $ref: '../responses/errors.yaml#/Forbidden'
          '404':
            $ref: '../responses/errors.yaml#/NotFound'
      delete:
        summary: Delete a copper print
        description: Deletes a copper print
        security:
          - BearerAuth: [ ]
        parameters:
          - $ref: '../parameters/path.yaml#/printId'
        responses:
          '204':
            description: Print deleted successfully
          '401':
            $ref: '../responses/errors.yaml#/Unauthorized'
          '403':
            $ref: '../responses/errors.yaml#/Forbidden'
          '404':
            $ref: '../responses/errors.yaml#/NotFound'

components:
  schemas:
    Gallery:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        printCount:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    GalleryCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
        translations:
          type: object
          properties:
            da:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
    GalleryUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        translations:
          type: object
          properties:
            da:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string

    GalleryList:
      type: object
      properties:
        galleries:
          type: array
          items:
            $ref: '#/Gallery'
        totalCount:
          type: integer
        currentPage:
          type: integer
        totalPages:
          type: integer

    GalleryDetail:
      allOf:
        - $ref: '#/components/schemas/Gallery'
        - type: object
          properties:
            prints:
              type: array
              items:
                $ref: '#/components/schemas/PrintSummary'

    Print:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        technique:
          type: string
        plateType:
          type: string
        dimensions:
          type: string
        year:
          type: integer
        editionSize:
          type: integer
        paperType:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    PrintCreate:
      type: object
      required:
        - title
        - technique
        - plateType
        - dimensions
        - year
        - editionSize
      properties:
        title:
          type: string
        description:
          type: string
        technique:
          type: string
        plateType:
          type: string
        dimensions:
          type: string
        year:
          type: integer
        editionSize:
          type: integer
        paperType:
          type: string
        translations:
          type: object
          properties:
            da:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
    PrintUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        technique:
          type: string
        plateType:
          type: string
        dimensions:
          type: string
        year:
          type: integer
        editionSize:
          type: integer
        paperType:
          type: string
        artistNotes:
          type: string
        translations:
          type: object
          properties:
            da:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
    PrintList:
      type: object
      properties:
        prints:
          type: array
          items:
            $ref: '#/components/schemas/PrintSummary'
        totalCount:
          type: integer
        currentPage:
          type: integer
        totalPages:
          type: integer

    PrintDetail:
      $ref: './schemas/print.yaml#/PrintDetail'
    PrintSummary:
      $ref: './schemas/print.yaml#/PrintSummary'
    Error:
      $ref: './schemas/error.yaml#/Error'

  responses:
    BadRequest:
      $ref: './responses/errors.yaml#/BadRequest'
    Unauthorized:
      $ref: './responses/errors.yaml#/Unauthorized'
    Forbidden:
      $ref: './responses/errors.yaml#/Forbidden'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '../schemas/error.yaml#/Error'
          example:
            error:
              code: "RESOURCE_NOT_FOUND"
              message: "The requested resource could not be found."
    GalleryListResponse:
      $ref: './responses/galleries.yaml#/GalleryListResponse'
    GalleryResponse:
      $ref: './responses/galleries.yaml#/GalleryResponse'
    GalleryDetailResponse:
      $ref: './responses/galleries.yaml#/GalleryDetailResponse'
    PrintListResponse:
      $ref: './responses/prints.yaml#/PrintListResponse'
    PrintResponse:
      $ref: './responses/prints.yaml#/PrintResponse'
    PrintDetailResponse:
      $ref: './responses/prints.yaml#/PrintDetailResponse'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT