openapi: 3.1.0
info:
  title: Copper Print Gallery Image Processing Service API
  version: 2.0.0
  description: API for processing, optimizing, and managing images in the Copper Print Gallery system

servers:
  - url: '{protocol}://{environment}.image.{domain}/api/v1'
    variables:
      protocol:
        enum: [http, https]
        default: https
      environment:
        enum: [dev, staging, prod]
        default: prod
      domain:
        default: api.copperprintgallery.com
        description: Base domain for the API

paths:
  /images:
    post:
      summary: Upload and process a new image
      description: Upload a new image, initiate processing, and store the result
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                options:
                  $ref: '#/components/schemas/ProcessingOptions'
      responses:
        '202':
          $ref: '#/components/responses/AsyncProcessingResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '415':
          $ref: '#/components/responses/UnsupportedMediaType'

  /images/{parentImageId}:
    get:
      summary: Retrieve image information
      description: Get information about a processed image and all its versions
      parameters:
        - name: parentImageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ImageInfoResponse'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete an image and all its versions
      description: Remove an image and all its processed versions from storage
      parameters:
        - name: parentImageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Image and all versions successfully deleted
        '404':
          $ref: '#/components/responses/NotFound'

  /images/{parentImageId}/status:
    get:
      summary: Check processing status
      description: Get the current status of an image processing operation
      parameters:
        - name: parentImageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ProcessingStatusResponse'
        '404':
          $ref: '#/components/responses/NotFound'

  /images/{parentImageId}/optimize:
    post:
      summary: Optimize an image
      description: Initiate an optimization process for an existing image
      parameters:
        - name: parentImageId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OptimizationOptions'
      responses:
        '202':
          $ref: '#/components/responses/AsyncProcessingResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

  /images/{parentImageId}/exif:
    get:
      summary: Retrieve EXIF data
      description: Get EXIF metadata for the original image
      parameters:
        - name: parentImageId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: '#/components/responses/ExifDataResponse'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  schemas:
    ProcessingOptions:
      type: object
      properties:
        customSizes:
          type: array
          items:
            $ref: '#/components/schemas/SizeOption'
        format:
          type: string
          enum: [jpg, webp]
        quality:
          type: integer
          minimum: 1
          maximum: 100
        preserveMetadata:
          type: boolean

    SizeOption:
      type: object
      properties:
        name:
          type: string
        width:
          type: integer
        height:
          type: integer
        fit:
          type: string
          enum: [cover, contain, fill, inside, outside]

    OptimizationOptions:
      type: object
      properties:
        quality:
          type: integer
          minimum: 1
          maximum: 100
        format:
          type: string
          enum: [jpg, webp]

    ProcessedImage:
      type: object
      properties:
        parentId:
          type: string
        versionId:
          type: string
        versionName:
          type: string
        originalName:
          type: string
        mimeType:
          type: string
        size:
          type: integer
        width:
          type: integer
        height:
          type: integer
        url:
          type: string
        storageDetails:
          type: object
          properties:
            bucket:
              type: string
            path:
              type: string

    ProcessingStatus:
      type: object
      properties:
        status:
          type: string
          enum: [pending, processing, completed, failed]
        progress:
          type: integer
          minimum: 0
          maximum: 100
        error:
          type: string

    ExifData:
      type: object
      additionalProperties: true

  responses:
    AsyncProcessingResponse:
      description: Asynchronous processing initiated
      content:
        application/json:
          schema:
            type: object
            properties:
              parentImageId:
                type: string
              status:
                type: string
                enum: [pending, processing]
              statusUrl:
                type: string

    ImageInfoResponse:
      description: Image information including all versions
      content:
        application/json:
          schema:
            type: object
            properties:
              parentImageId:
                type: string
              original:
                $ref: '#/components/schemas/ProcessedImage'
              versions:
                type: array
                items:
                  $ref: '#/components/schemas/ProcessedImage'

    ProcessingStatusResponse:
      description: Current status of image processing
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProcessingStatus'

    ExifDataResponse:
      description: EXIF metadata for the original image
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExifData'

    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string

    UnsupportedMediaType:
      description: Unsupported media type
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []